### ISSUE TITLE
Curious onlooker

### ISSUE THREAD

**Issue by PaperclipAdmirer418** [map220v/TencentPvZOL#1]
Hey, I learned of you and this project from someone on youtube and I'm curious to know if you are still working on this game or not.

**Comment by map220v** [comment]
Im not working on this project anymore(too much code requires fixing and flash is not supported anymore). 

Im right now interested in popcap official PvZ port to C# (https://github.com/map220v/LAWN) and leaked PvZ beta versions with debug symbols(.pdb file)

**Comment by Bobotka** [comment]
> Im not working on this project anymore(too much code requires fixing and flash is not supported anymore).
> 
> Im right now interested in popcap official PvZ port to C# (https://github.com/map220v/LAWN) and leaked PvZ beta versions with debug symbols(.pdb file)

Could you at least tell us how to access the .bbone files? (viewing)

**Comment by map220v** [comment]
> > Im not working on this project anymore(too much code requires fixing and flash is not supported anymore).
> > Im right now interested in popcap official PvZ port to C# (https://github.com/map220v/LAWN) and leaked PvZ beta versions with debug symbols(.pdb file)
> 
> Could you at least tell us how to access the .bbone files? (viewing)

it's proprietary animation format, only this code can read and view it.
https://github.com/map220v/TencentPvZOL/tree/main/src/asgui/blit

**Comment by Bobotka** [comment]
> > > Im not working on this project anymore(too much code requires fixing and flash is not supported anymore).
> > > Im right now interested in popcap official PvZ port to C# (https://github.com/map220v/LAWN) and leaked PvZ beta versions with debug symbols(.pdb file)
> > 
> > 
> > Could you at least tell us how to access the .bbone files? (viewing)
> 
> it's proprietary animation format, only this code can read and view it. https://github.com/map220v/TencentPvZOL/tree/main/src/asgui/blit

Ah, so like, is it really possible to find a way to view the spritesheets and the animations with the fact that i've been given the code for the blitbone files and knowledge of actionscript? Sounds like the files are still accessible despite being propertiary, since it seems that they use zlib compression
